#ifndef CONSTANTS_H
#define CONSTANTS_H

typedef enum JankeyState {
    JANKEY_STATE_RUNNING_TEST,
    JANKEY_STATE_DISPLAYING_POST_TEST_MODAL,
    JANKEY_STATE_QUITTING
} JankeyState;

#define WORDS_PER_TEST (size_t)25
#define MAX_CHARS_PER_LINE 66
#define MAX_TEST_WIN_ROWS 3
#define MIN_WIN_WIDTH 24

#define COLOR_PAIR_WHITE 3
#define COLOR_PAIR_GREEN 1
#define COLOR_PAIR_RED 2

#endif
